### ISSUE TITLE
HELP！！Programming language and database selection problem

### ISSUE THREAD

**Issue by warmilk** [dcmjs-org/dicomweb-server#69]
Why choose node and couchDB? 

Do they have any advantages over other programming languages and databases? 

Because our company is also facing the problem of choosing the DICOM server technology stack, Our company lacks experience in building dicom services， want to hear your suggestions ~~~❤

**Comment by pieper** [comment]
In this dcmjs-org group we are building a suite of libraries to work with dicom using JavaScript, so node is the logical platform to use for servers.  The current implementation separates the DICOMweb API from the back-end database, so one could use something other than CouchDB as needed.

There are many other options for DICOMweb, like dcm4chee in Java, orthanc in C++, plus some C# implementations and also Google's service offering.  A key thing is that they expose a standard interface so that clients don't need to care about the implementation (this is not quite true yet, but it's a design goal).

I'll close this now but feel free to post follow up questions as specific issues.
